
[ruin]
order = 1
name = "Ruins"
tileset = "ruin"
levels = 3
enemies = ["ruin-mechanic", "ruin-security1", "ruin-security2", "ruin-security3", "ruin-dog", "ruin-turret", "ruin-messenger", "ruin-speed_turret", "ruin-sentry", "ruin-scientist", "ruin-wall"]
treasure = ["flute", "antishovel", "crickets", "exoskeleton", "accelerator"]
narration = """{portrait:static} ...
{sound:hello} ... Hello? ...
{portrait:gc} Hey, are you still alive?
Cool.
...
Look, I haven't really been paying attention. Did you find the treasure yet?
Come on, I know it's your first job, but it's not that hard.
Anyway, I've turned my radio back on. {color:red} Good luck! {color:normal}"""
# short: "Hello?" (worried for self due to neglecting duties as mission control person)

#[lab]
#order = 2
#name = "Lab"
#tileset = "lab"
#levels = 3
#enemies = ["ruin-mechanic", "ruin-security1", "ruin-security2", "ruin-security3", "ruin-dog", "ruin-turret", "ruin-messenger", "lab-turret", "ruin-sentry", "lab-scientist", "lab-wall"]
#treasure = ["flute", "antishovel", "crickets", "exoskeleton", "accelerator", "enlargener", "tarski_field", "void_pants", "magnet_shield", "nano_blood", "rocket_shoes", "overclock", "dog"]
#narration = "There's probably some fancy stuff in there. Make sure to bring it all back with you!"

#[power_plant]
#order = 3
#name = "Power Plant"
#tileset = "power_plant"
#levels = 3
#enemies = ["power-electrician", "ruin-security1", "ruin-security2", "ruin-security3", "ruin-dog", "ruin-turret", "ruin-messenger", "lab-turret", "ruin-sentry", "lab-scientist", "lab-wall"]
#treasure = ["flute", "antishovel", "crickets", "exoskeleton", "accelerator", "enlargener", "tarski_field", "void_pants", "magnet_shield", "nano_blood", "rocket_shoes", "overclock", "dog", "heat_shield", "dampener"]
#narration = "They used geothermal energy, so you must be close to the end. Good luck!"
