[ruin]
tileset = "ruin"
levels = 3
enemies = ["ruin.mechanic", "ruin.security", "ruin.dog", "ruin.turret"]
treasure = []
narration = """
{portrait:static}...
...Hello?...
{portrait:gc}Hey, are you still alive?
Cool.
...
Look, I haven't really been paying attention. Did you find the treasure yet?
Come on, I know it's your first job, but it's not that hard.
Anyway, I've turned my radio back on. Good luck!"""

[lab]
tileset = "lab"
levels = 3
enemies = []
treasure = []
narration = "There's probably some fancy stuff in there. Make sure to bring it all back with you!"