'0' = """
.XXX
X.XX
XX.X
X..X
XXX"""
'1' = """
XX.
.X.
.X.
.X.
XXX"""
'2' = """
.XX.
X..X
..X.
.X..
XXXX"""
'3' = """
XXXXX
....X
...X.
X...X
.XXX"""
'4' = """
..XX.
.X.X.
X..X.
XXXXX
...X"""
'5' = """
XXXX
X...
XXX.
...X
XXX"""
'6' = """
.XXX
X...
XXX.
X..X
.XX"""
'7' = """
XXXXX
...X.
..X..
.X...
.X"""
'8' = """
XXXX
X..X
.XX.
X..X
XXXX"""
'9' = """
.XXX
X..X
.XXX
...X
.XX"""
'a' = """
....
.XX
X..X
X..X
.XXX"""
'b' = """
X....
XXX.
X..X
X..X
XXX"""
'c' = """
....
.XX
X..
X...
.XX"""
'd' = """
...X
.XXX
X..X
X..X
.XXX"""
'e' = """
....
.XXX
XXXX
X...
.XXX"""
'f' = """
..XX
.X.X
.X..
XXX.
.X..
.X"""
'g' = """
....
.XXX
X..X
.XXX
...X
.XXX"""
'h' = """
X...
XXX...
X..X.
X..X
X..X"""
'i' = """
X..
...
X..
X..
X"""
'j' = """
...X
....
...X
...X
X..X
.XX"""
'k' = """
....
X.X..
XX...
X.X..
X.X"""
'l' = """
X..
X..
X..
X..
.X"""
'm' = """
.....
.X.X.
X.X.X
X.X.X
X.X.X"""
'n' = """
.....
X.X.
XX.X
X..X
X..X"""
'o' = """
.XX.
X..X
X..X
.XX"""
'p' = """
....
XXX.
X..X.
XXX.
X"""
'q' = """
....
....
.XXX
X..X
.XXX
...X"""
'r' = """
....
.X..
X...
X...
X"""
's' = """
...
.X...
X.
.X
X..."""
't' = """
.X.
XXX
.X.
.X.
..X"""
'u' = """
....
X..X
X..X
X..X
.XXX"""
'v' = """
.....
X...X
X...X
.X.X.
..X.."""
'w' = """
.....
X...X
X...X
X.X.X
.X.X"""
'x' = """
...
X.X.
.X.
.X.
X.X"""
'y' = """
....
....
X..X
.XXX
...X
.XXX"""
'z' = """
....
XXXX
..X.
.X..
XXXX"""
'A' = """
.XXX.
X...X
XXXXX
X...X
X...X"""
'B' = """
XXX.
X..X
XXX.
X..X
XXX."""
'C' = """
.XX.
X..X
X...
X..X
.XX."""
'D' = """
XXX.
X..X
X..X
X..X
XXX."""
'E' = """
XXXX
X...
XXX.
X...
XXXX"""
'F' = """
XXXX
X...
XXX.
X...
X..."""
'G' = """
.XXX
X...
X.XX
X..X
.XXX"""
'H' = """
X..X
X..X
XXXX
X..X
X..X"""
'I' = """
XXX
.X.
.X.
.X.
XXX"""
'J' = """
..XX
...X
...X
X..X
.XX.
....
"""
'K' = """
X..X
X.X.
XX..
X.X.
X..X"""
'L' = """
X....
X....
X....
X....
XXXX."""
'M' = """
XX.XX
XXXXX
X.X.X
X.X.X
X...X"""
'N' = """
X...X
XX..X
X.X.X
X..XX
X...X"""
'O' = """
.XX.
X..X
X..X
X..X
.XX."""
'P' = """
XXX.
X..X
XXX.
X...
X..."""
'Q' = """
.XX..
X..X.
X..X.
X.XX.
.XXX.
....X"""
'R' = """
XXX.
X..X
XXX.
X.X.
X..X"""
'S' = """
.XXX
X...
.XX.
...X
XXX."""
'T' = """
XXXXX
..X..
..X..
..X..
..X.."""
'U' = """
X...X
X...X
X...X
X...X
.XXX."""
'V' = """
X...X
X...X
X...X
.X.X.
..X.."""
'W' = """
X...X
X.X.X
X.X.X
X.X.X
.X.X."""
'X' = """
X...X
.X.X.
..X..
.X.X.
X...X"""
'Y' = """
X...X
.X.X.
..X..
..X..
..X.."""
'Z' = """
XXXXX
...X.
..X..
.X...
XXXXX"""
'!' = """
X..
X..
X..
...
X.."""
'"' = """
X.X.
X.X.
....
....
...."""
'$' = """
.XXXX
X.X..
.XXX.
..X.X
XXXX."""
'%' = """
XX..X
X..X.
..X..
.X..X
X..XX
"""
"'" = """
X..
X..
...
...
..."""
'[' = """
..X
.X.
X..
X..
.X.
..X"""
')' = """
X..
.X.
..X
..X
.X.
X.."""
'+' = """
..X..
..X..
XXXXX
..X..
..X.."""
',' = """
...
...
...
...
XX.
.X."""
'-' = """
....
....
XXXX"""
'.' = """
....
....
....
XX..
XX..
...."""
'/' = """
..X
..X
.X.
.X.
X..
X.."""
':' = """
...
X..
...
...
X.."""
'?' = """
XXX..
..X.
.X..
....
.X.."""
';' = """
...
....
...
....
XX..
.X."""
'_' = """
...
....
...
....
XXXX.."""
