"Title_Title" = "Dig Site 8"
"Title_Credits" = "Credits"
"Title_Begin" = "Explore the Site"
"Title_Beastiary" = "View the Beastiary"
"Title_Itemiary" = "View the Treasure Codex"
"Title_Soundiary" = "Sound Test"


"Soundiary_Cool" = "Cool"
"Soundiary_Octojam" = "Octojam"
"Soundiary_Five" = "Five"
"Soundiary_Title" = "Title"
"Soundiary_PhoneHey" = "PhoneHey"
"Soundiary_Ruin" = "Ruin"
"Soundiary_WelcomeBack" = "WelcomeBack"
"Soundiary_Hello" = "Hello"


"Credits_1" = "Credits Go Here"
"New_Level" = "Now Entering"
"End_Win_Msg" = "You Win!!"
"Char_Name" = "Name:"
"Char_Height" = "Height:"
"Char_Build" = "Build:"
"Char_Eyes" = "Eyes:"

"Char_Height_0" = "Average"
"Char_Height_1" = "Short"
"Char_Height_2" = "Above Average"
"Char_Height_3" = "Very Tall"

"Char_Build_0" = "A Little Extra"
"Char_Build_1" = "Curvy"
"Char_Build_2" = "Full Figured"
"Char_Build_3" = "Skinny"
"Char_Build_4" = "Average"
"Char_Build_5" = "Fit"
"Char_Build_6" = "Jacked"
"Char_Build_7" = "Rather Not Say"

"Char_Eyes_0" = "Blue"
"Char_Eyes_1" = "Brown"
"Char_Eyes_2" = "Green"
"Char_Eyes_3" = "Hazel"
"Char_Eyes_4" = "Black"
"Char_Eyes_5" = "Grey"
"Char_Eyes_6" = "Red"
"Char_Eyes_7" = "Shifty"
