[weapon-spiderpincer]
Type = "melee"
Damage = "1-3"
AttackDescription = [ "pincer", "mandible" ]

[weapon-fist]
Type = "melee"
Damage = "1-3"
AttackVerb = [ "fist", "knuckles"]
AttackNoun = [ "punches", "?"]
